version: "2"
services:
  node:
    image: "node:lts-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - .:/home/node/app
    ports:
      - 8081:8081
    command: "npm start"
  mongo:
    image: "mongo:latest"
    restart: always
    ports:
      - 27017:27017